name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create .env file for cadvmetrics
        run: |
          echo "TARGET_URL=${{ secrets.TARGET_URL }}" >> .env

      - name: Create key and crt for https
        run: |
          echo "${{ secrets.CRT }}" > secret/ok_server.crt
          echo "${{ secrets.KEY }}" > secret/ok_server.key
          
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build&Push
        run: |
          docker build -t cashadvisorbeta/cadv_metrics:latest .
          docker push cashadvisorbeta/cadv_metrics:latest